### ISSUE TITLE
Startup Issue

### ISSUE THREAD

**Issue by xXumarkuXx** [InventivetalentDev/PluginBlueprint#10]
Any version past 1.0.3 will not open up and just cause an error

![pluginblueprint_2018-11-19_17-46-35](https://user-images.githubusercontent.com/17567502/48744541-de753080-ec24-11e8-96e9-076c94865bef.png)

**Comment by InventivetalentDev** [comment]
Does this happen when opening the editor itself or when you open a project?

**Comment by xXumarkuXx** [comment]
The editor itself after installing ethier version 1.0.4 and 1.0.5
I had also tried in both cases to uninstall and remove the folder to install it fresh and it still didn't work

**Comment by InventivetalentDev** [comment]
fixed in v1.0.6
