### ISSUE TITLE
Suggestion for an Undo and Redo

### ISSUE THREAD

**Issue by xXumarkuXx** [InventivetalentDev/PluginBlueprint#11]
It would be nice to see some way to undo and redo, for example to undo deleted code blocks so we don't have to search for it and its outputs again would be a nice feature to see added.

**Comment by InventivetalentDev** [comment]
Yep! Very high on my TODOs, I know the pain of redoing stuff manually :)

**Comment by InventivetalentDev** [comment]
Added in 1.0.7
