### ISSUE TITLE
Please make the AppImage available for download

### ISSUE THREAD

**Issue by probonopd** [InventivetalentDev/PluginBlueprint#12]
https://github.com/InventivetalentDev/PluginBlueprint/blob/6710f424245dc68389c2ea23924c7fc1877cc4e5/package.json#L14

Please make the AppImage available for download on https://github.com/InventivetalentDev/PluginBlueprint/releases. Thanks!

**Comment by InventivetalentDev** [comment]
Won't publish it to github, but I can add it to the zip download

**Comment by InventivetalentDev** [comment]
added to the download.

**Comment by probonopd** [comment]
Please DO NOT put an AppImage into another archive like a .zip, as explained in https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake. Only if we have a download URL that gives us an unzipped AppImage can we add it to the AppImageHub catalog of available AppImages (=free advertising).

**Comment by probonopd** [comment]
Hi @InventivetalentDev I guess an AppImage inside a zip is better than none at all ;-) 

If you like I can help promoting your application, e.g., on https://appimage.github.io/apps/ but that would require it to be downloadable in unzipped AppImage format. And yes, I am from the AppImage organization - I hope this does not take away from the validity of my original feature request. Thanks!
