### ISSUE TITLE
StringConstant bug

### ISSUE THREAD

**Issue by Cactusje** [InventivetalentDev/PluginBlueprint#14]
Hello!

I found this bug when using StringConstant.

This is what happens when I put a long text in it:
![image](https://user-images.githubusercontent.com/28195796/50980759-be157400-14f9-11e9-8a74-6bd08d7876c2.png)

Then is what happens when I clone it:
![image](https://user-images.githubusercontent.com/28195796/50980808-d2f20780-14f9-11e9-9f78-b36d6a78f213.png)

It should be nice if the StringConstant automatically changes or even better, with a hover function so if you have a very large text and you click on it it will all show up :)

Thanks,
Jorrit

**Comment by InventivetalentDev** [comment]
Will be fixed in the next version
