### ISSUE TITLE
Cant open projects

### ISSUE THREAD

**Issue by FranciscoSolisMaturana** [InventivetalentDev/PluginBlueprint#16]
## Which version are you using?
1.1.2 - Windows

## What steps will reproduce the problem?  
1. I click on recent projects.

## What were you expecting to happen? What happened instead?  
Open my project an use the app; I cant open my projects

**Comment by InventivetalentDev** [comment]
Please try opening your project directly (File -> Open) and see if it shows up in the recent project list after saving it.

**Comment by FranciscoSolisMaturana** [comment]
doesnt work... i tried with doubleclick the .pbp file, open with File -> Open adn with Open Project Button

**Comment by InventivetalentDev** [comment]
Did you finish the project setup? (i.e. choose directory -> add spigot.jar -> create nodes -> save)  

Would be great if you could upload the .pbp file, so I can check if there's something wrong with that.

**Comment by FranciscoSolisMaturana** [comment]
yes, but new it works, I changed my version from 1.1.2 to 1.1.0

**Comment by FranciscoSolisMaturana** [comment]
I changed again to 1.1.2, here is the .pbp file

[TPSAPI.zip](https://github.com/InventivetalentDev/PluginBlueprint/files/2818452/TPSAPI.zip)

**Comment by xLengoBug5** [comment]
I’m having this issue also.

**Comment by FranciscoSolisMaturana** [comment]
yes, it opens fine in 1.1.0, but I do the same thing, i think is a problem of the version...

**Comment by FranciscoSolisMaturana** [comment]
this is what i do:

Create New Project -> Select file TPSAPI -> Select spigot_1.13.2.jar from buildtools.

**Comment by InventivetalentDev** [comment]
But did you save the project at any point?

**Comment by FranciscoSolisMaturana** [comment]
No, it didn't open the editor, only appears the main page

**Comment by FranciscoSolisMaturana** [comment]
I've saved the project in the version 1.1.1 but it doesnt opens in 1.1.2, I think isn't incorrect saving, I think is a problem while opening project

**Comment by InventivetalentDev** [comment]
Should be fixed in 1.1.3
