### ISSUE TITLE
I can’t open my project!

### ISSUE THREAD

**Issue by xLengoBug5** [InventivetalentDev/PluginBlueprint#17]
## Which version are you using?
The latest version.

## What steps will reproduce the problem?  
1. Create a project
2. Open the project
3. Nothing happens.

## What were you expecting to happen? What happened instead?  
I expected it to open the project but it didn’t.

**Comment by InventivetalentDev** [comment]
> 1. Create a project
> 2. Open the project
> 3. Nothing happens.

So are you actually *opening* an existing project, or are you creating a new one?

**Comment by InventivetalentDev** [comment]
Duplicate of #16
