### ISSUE TITLE
I cant add Bukkit object & method

### ISSUE THREAD

**Issue by FranciscoSolisMaturana** [InventivetalentDev/PluginBlueprint#18]
## Which version are you using?
latest

## What steps will reproduce the problem?  
1. Right Click Screen
2. Click add Bukkit Object or Bukkit Method

## What were you expecting to happen? What happened instead?  
Add JavaPlugin Object or Add onEnable() method; Open a window what it says i having issues

**Comment by InventivetalentDev** [comment]
Sentry issue: [PLUGINBLUEPRINT-30](https://sentry.io/inventivetalent/pluginblueprint/issues/845983814/?referrer=github_plugin)
