### ISSUE TITLE
Make it easier to scroll up and down long lists

### ISSUE THREAD

**Issue by shawngiese** [InventivetalentDev/PluginBlueprint#3]
For example, I want the Player getLocation and getWorld but I have a lot of wheel scrolling to get the method I want. Would be great if we could type the first letter (or first few letters) to quickly get to where we want... or enable the arrows or page up/down to move faster.

Just a feature request.

**Comment by InventivetalentDev** [comment]
Scroll speed is now increased for longer lists in the latest versions.
