### ISSUE TITLE
Tried to get a variable and interface stopped working

### ISSUE THREAD

**Issue by shawngiese** [InventivetalentDev/PluginBlueprint#4]
I was trying to get a variable I had set and the box that appeared for get was empty. Then there was only the plus sign. When I closed and opened the project, some boxes were missing and some connectors were floating, unconnected to anything.

I could edit the graph.pbg file to remove the offending tag. Then my file worked fine.

For example, here is a new project where I tried to add a node to get a variable:
{
  "config": {},
  "groups": [],
  "last_link_id": 1,
  "last_node_id": 3,
  "links": [],
  "nodes": [
    {
      "flags": {},
      "id": 2,
      "inputs": [
        {
          "color_off": "#911500",
          "color_on": "#f62000",
          "link": null,
          "name": "EXEC",
          "shape": 5,
          "type": "@EXEC"
        },
        {
          "label": "myVariable",
          "link": null,
          "name": "myVariable",
          "type": 0
        }
      ],
      "mode": 0,
      "pos": [
        168,
        171
      ],
      "properties": {
        "name": "myVariable"
      },
      "size": {
        "type": "Buffer",
        "data": [
          0,
          0,
          12,
          67,
          0,
          0,
          8,
          66
        ]
      },
      "type": "variables/Set"
    },
    {
      "flags": {},
      "id": 3,
      "mode": 0,
      "outputs": [
        {
          "links": null,
          "name": "myVariable",
          "type": null
        }
      ],
      "pos": [
        288,
        260
      ],
      "properties": {
        "name": "myVariable"
      },
      "size": {
        "type": "Buffer",
        "data": [
          0,
          0,
          12,
          67,
          0,
          0,
          152,
          65
        ]
      },
      "type": "variables/Get"
    }
  ]
}

**Comment by InventivetalentDev** [comment]
Sentry issue: [PLUGINBLUEPRINT-W](https://sentry.io/inventivetalent/pluginblueprint/issues/762812414/)
