### ISSUE TITLE
Have error messages correspond with onscreen elements

### ISSUE THREAD

**Issue by shawngiese** [InventivetalentDev/PluginBlueprint#7]
Maybe intercept the error messages and replace names like "node_174_output_1 = node_183.equalsIgnoreCase(node_163_output_0)" with the names of objects that are visible.

From the UI those "nodes" do not reference anything I can see.

**Comment by InventivetalentDev** [comment]
So you're talking about console errors? Was planning on trying to add that to the visual debugging stuff to highlight the nodes that were involved in the error.

**Comment by shawngiese** [comment]
I mean the compilation errors I get when I try to compile the blueprint.

**Comment by InventivetalentDev** [comment]
A right. Think I can add that as well.

**Comment by InventivetalentDev** [comment]
added in v1.0.6
