### ISSUE TITLE
Removing slot breaks connection

### ISSUE THREAD

**Issue by shawngiese** [InventivetalentDev/PluginBlueprint#9]
The following steps corrupt my blueprint:
1. Create Java.lang.String
2. Add output toString
3. Add output equalsIgnoreCase(String)
4. Double click on equalsIgnoreCase(String) to create String//equalsIgnoreCase
5. Remove output toString

Now the blueprint connector to String//equalsIgnoreCase is broken. If you save and open the project it will be empty and nothing new can be added.

**Comment by InventivetalentDev** [comment]
jagenjo/litegraph.js#56

**Comment by InventivetalentDev** [comment]
fixed in v1.0.6
